Repository GSG-G13/gym-server, pull requests merged in 2023-07, with the labels that each got.

#104 add main endpoint
  src/app.ts
Labels: waiting-review

#102 bugs fixing
  src/controllers/announcement/getannouncements.ts
  src/controllers/classes/addClass.ts
  src/controllers/classes/getClassById.ts
  src/controllers/classes/getClasses.ts
  src/controllers/orders/getOrders.ts
  src/controllers/orders/getUserOrders.ts
  src/controllers/products/addProduct.ts
  src/controllers/products/getProductByCategory.ts
  src/controllers/products/getProductById.ts
  src/controllers/products/getProducts.ts
  src/controllers/reviews/addreview.ts
  src/controllers/reviews/getreviews.ts
  src/controllers/subscriptions/getClassSubscription.ts
  src/controllers/subscriptions/getSubscriptions.ts
  src/controllers/subscriptions/getUserSubscriptions.ts
  src/controllers/subscriptions/updateSubscription.ts
  src/controllers/user/getallusers.ts
  src/database/productSchema.ts
  src/database/reviews.ts
  src/interfaces/product.ts
  src/routers/category/index.ts
  src/routers/class.ts
  src/routers/product.ts
  src/routers/reviews/index.ts
  src/routers/subscription.ts
Labels: waiting-review

#106 get all trainers
  src/controllers/user/getTrainers.ts
  src/routers/user/index.ts
Labels: approved

#108 fix class schema
  src/database/classSchema.ts
Labels: waiting-review

#112 add cors policy middleware
  package-lock.json
  package.json
  src/app.ts
  src/database/user.ts
Labels: waiting-review

#111 send user data to front
  src/controllers/user/signin.ts
Labels: approved

#114 add description for product schema, validation and interface
  src/database/productSchema.ts
  src/interfaces/product.ts
  src/validations/productValidationSchema.ts
Labels: waiting-review

#116 115 delete product by category controller
  src/controllers/products/getProductByCategory.ts
  src/controllers/products/index.ts
  src/routers/category/index.ts
  src/routers/product.ts
  src/validations/productValidationSchema.ts
Labels: waiting-review

#118 description controller
  src/controllers/products/addProduct.ts
Labels: waiting-review

#120 add createdAt for announcement schema
  src/database/announcement.ts
Labels: waiting-review

#122 change order router and controller
  src/controllers/orders/createOrder.ts
  src/routers/order.ts
Labels: waiting-review

#126 change product controller and router
  src/controllers/products/addProduct.ts
  src/routers/product.ts
Labels: waiting-review

#123 updata add announcmennt controller
  src/controllers/announcement/addannouncement.ts
  src/controllers/announcement/updateacnnouncement.ts
Labels: waiting-review

#128 change subscription controller
  src/controllers/subscriptions/addSubscription.ts
Labels: waiting-review

#131 check get orders
  src/controllers/orders/getOrders.ts
Labels: waiting-review

#133 check get subscription
  src/controllers/subscriptions/getSubscriptions.ts
Labels: waiting-review

#135 change controllers and fix getting body data
  src/controllers/announcement/addannouncement.ts
  src/controllers/orders/createOrder.ts
  src/controllers/products/addProduct.ts
  src/controllers/user/getallusers.ts
  src/controllers/user/signin.ts
  src/controllers/user/signup.ts
  src/database/user.ts
  src/routers/announcement/index.ts
  src/routers/user/index.ts
Labels: approved

#141 change for edit and delete data
  src/controllers/index.ts
  src/controllers/orders/getOrders.ts
  src/controllers/subscriptions/deleteSubscription.ts
  src/controllers/subscriptions/getSubscriptions.ts
  src/controllers/user/deleteUser.ts
  src/routers/announcement/index.ts
  src/routers/user/index.ts
Labels: waiting-review

#139 log out and remove cookie
  src/controllers/user/signOut.ts
  src/routers/user/index.ts
Labels: waiting-review

#137 add chat functionality with sockit io, delete app file and moved all …
  package-lock.json
  package.json
  src/app.ts
  src/controllers/chat/index.ts
  src/database/chat.ts
  src/index.ts
  src/routers/chat/index.ts
  src/routers/index.ts
Labels: approved

#145 add, get and delete comment functionality
  src/controllers/comments/addComment.ts
  src/controllers/comments/deleteComment.ts
  src/controllers/comments/getComments.ts
  src/controllers/comments/index.ts
  src/controllers/index.ts
  src/controllers/products/addProduct.ts
  src/controllers/products/getProducts.ts
  src/controllers/products/updateProduct.ts
  src/controllers/subscriptions/getSubscriptions.ts
  src/database/comment.schema.ts
  src/routers/comment/index.ts
  src/routers/index.ts
Labels: waiting-review

#147 fix update announcement controller to get body data
  src/controllers/announcement/updateacnnouncement.ts
  src/controllers/user/updatauser.ts
  src/routers/user/index.ts
Labels: waiting-review

#143 delete user
  src/controllers/index.ts
  src/controllers/user/deleteUserInfo.ts
  src/controllers/user/signOut.ts
  src/controllers/user/signin.ts
  src/controllers/user/signup.ts
  src/routers/user/index.ts
Labels: waiting-review

#148 add validation comment
  src/controllers/subscriptions/getSubscriptions.ts
  src/routers/comment/index.ts
  src/validations/commentValidationSchema.ts
Labels: waiting-review

#152 user reset his password
  src/controllers/index.ts
  src/controllers/user/changePassword.ts
  src/routers/user/index.ts
Labels: approved

#151 get one user
  src/controllers/index.ts
  src/controllers/user/getUserById.ts
  src/routers/user/index.ts
Labels: approved

#154 fix chat connection to get users data
  src/controllers/chat/index.ts
  src/index.ts
Labels: waiting-review

#158 New
  src/controllers/subscriptions/getSubscriptions.ts
  src/controllers/user/signup.ts
  src/controllers/user/updatauser.ts
  src/middlewares/checkRole.ts
Labels: waiting-review

#160 add description
  src/controllers/products/updateProduct.ts
  src/routers/user/index.ts
Labels: waiting-review

#162 remove check role delete subscription router
  src/routers/subscription.ts
Labels: waiting-review

#164 add age field to be updated and remove check role from get subs
  src/controllers/user/signup.ts
  src/controllers/user/updatauser.ts
  src/routers/subscription.ts
Labels: waiting-review

#166 add update order status controller and router
  src/controllers/orders/updateOrder.ts
  src/routers/category/index.ts
  src/routers/order.ts
Labels: waiting-review

#168 add,get calendar
  src/controllers/calendar/addCalendar.ts
  src/controllers/calendar/getCalendar.ts
  src/controllers/calendar/getCalendarByClassId.ts
  src/controllers/index.ts
  src/database/calendar.ts
  src/interfaces/calendar.ts
  src/routers/calendar/index.ts
  src/routers/index.ts
Labels: in-progress

#169 delete one calendar data controller and data
  src/controllers/calendar/addCalendar.ts
  src/controllers/calendar/deleteCalendar.ts
  src/controllers/index.ts
  src/routers/calendar/index.ts
Labels: waiting-review
