Repository GSG-G13/gym-server, pull requests merged in 2023-06, with the labels that each got.

#9 fix mongodb connection
  src/config/index.ts
  src/index.ts
Labels: approved

#12 add signup function
  src/config/index.ts
  src/controllers/user/signup.ts
  src/database/user.ts
  src/routers/userroutes/index.ts
Labels: approved

#19 validation middleware
  src/middlewares/validation.ts
Labels: approved, done

#15 4 signup
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/user/signup.ts
  src/database/user.ts
  src/index.ts
  src/interfaces/requestI.ts
  src/interfaces/userDataI.ts
  src/middlewares/checkAuth.ts
  src/middlewares/validation.ts
  src/routers/index.ts
  src/routers/userroutes/index.ts
  src/validations/index.ts
  src/validations/signupValidationSchema.ts
Labels: waiting-review

#21 5 create product
  src/controllers/announcement/addannouncement.ts
  src/controllers/products/addProduct.ts
  src/controllers/products/index.ts
  src/database/productSchema.ts
  src/interfaces/product.ts
  src/middlewares/validation.ts
  src/routers/index.ts
  src/routers/product.ts
  src/validations/productValidationSchema.ts
Labels: waiting-review

#22 6 create class
  src/controllers/classes/addClass.ts
  src/database/classSchema.ts
  src/interfaces/class.ts
  src/routers/class.ts
  src/routers/index.ts
  src/validations/classesValidationSchema.ts
  tsconfig.json
Labels: waiting-review

#25 review feature post method
  src/controllers/reviews/addreview.ts
  src/controllers/user/signup.ts
  src/database/reviews.ts
  src/interfaces/userDataI.ts
  src/routers/index.ts
  src/routers/reviews/index.ts
  src/routers/user/index.ts
Labels: approved

#28 get products
  src/controllers/products/getProducts.ts
  src/controllers/products/index.ts
  src/routers/index.ts
  src/routers/product.ts
Labels: waiting-review

#32 26 get classes
  src/controllers/classes/getClasses.ts
  src/controllers/classes/index.ts
  src/routers/class.ts
Labels: approved

#36 delete annoouncement
  src/controllers/announcement/deleteannouncement.ts
  src/routers/announcement/index.ts
Labels: waiting-review

#37 get product by id controller and router
  src/controllers/products/getProductById.ts
  src/controllers/products/index.ts
  src/routers/product.ts
Labels: waiting-review

#45 delete product controller and router
  src/controllers/products/deleteProduct.ts
  src/controllers/products/index.ts
  src/routers/product.ts
Labels: waiting-review

#44 update announcement
  src/controllers/announcement/updateacnnouncement.ts
  src/routers/announcement/index.ts
Labels: waiting-review

#47 update product
  src/controllers/products/index.ts
  src/controllers/products/updateProduct.ts
  src/routers/product.ts
Labels: waiting-review

#56 42 delete class
  src/controllers/classes/addClass.ts
  src/controllers/classes/deleteClass.ts
  src/controllers/classes/getClasses.ts
  src/controllers/classes/index.ts
  src/routers/class.ts
Labels: waiting-review

#60 add subscribtion controller and router
  src/controllers/subscriptions/addSubscription.ts
  src/controllers/subscriptions/index.ts
  src/database/subscriptionSchema.ts
  src/interfaces/subscription.ts
  src/routers/subscription.ts
Labels: waiting-review

#48 get reviews by product ID
  src/controllers/reviews/getreviews.ts
  src/routers/reviews/index.ts
Labels: waiting-review

#64 add category schema, interface, schema and router
  src/controllers/categories/addCategory.ts
  src/controllers/categories/index.ts
  src/controllers/index.ts
  src/database/category.schema.ts
  src/interfaces/category.ts
  src/routers/category/index.ts
Labels: waiting-review

#58 update class controller and router
  src/controllers/classes/index.ts
  src/controllers/classes/updateClass.ts
  src/routers/class.ts
Labels: waiting-review

#53 delete a review
  src/controllers/reviews/deletereview.ts
  src/routers/reviews/index.ts
Labels: waiting-review

#73 modify add category contoller
  src/controllers/categories/addCategory.ts
Labels: waiting-review

#71 get all categories
  src/controllers/categories/getCategories.ts
  src/controllers/categories/index.ts
  src/controllers/index.ts
  src/routers/category/index.ts
Labels: waiting-review

#74 update category
  src/controllers/categories/index.ts
  src/controllers/categories/updateCategory.ts
  src/controllers/index.ts
  src/routers/category/index.ts
Labels: waiting-review

#76 61 get subscribtions
  src/controllers/subscriptions/getSubscriptions.ts
  src/controllers/subscriptions/index.ts
  src/routers/subscription.ts
Labels: waiting-review

#78 delete category
  src/controllers/categories/deleteCategory.ts
  src/controllers/categories/index.ts
  src/controllers/index.ts
  src/routers/category/index.ts
Labels: waiting-review

#80 New get all users
  src/controllers/reviews/deletereview.ts
  src/controllers/user/getallusers.ts
  src/routers/user/index.ts
Labels: waiting-review

#68 New sign in
  src/controllers/user/signin.ts
  src/routers/user/index.ts
  src/validations/loginvalidation.ts
Labels: waiting-review

#81 79 get users subscription
  src/controllers/subscriptions/getUserSubscriptions.ts
  src/controllers/subscriptions/index.ts
  src/routers/subscription.ts
Labels: approved

#83 82 get class subscription
  src/controllers/subscriptions/getClassSubscription.ts
  src/controllers/subscriptions/index.ts
  src/routers/subscription.ts
Labels: waiting-review

#85 84 update subscription controller and router
  src/controllers/subscriptions/index.ts
  src/controllers/subscriptions/updateSubscription.ts
  src/routers/subscription.ts
Labels: approved

#88 delete subscription controller and router
  src/controllers/subscriptions/deleteSubscription.ts
  src/controllers/subscriptions/index.ts
  src/routers/subscription.ts
Labels: waiting-review

#41 get product by category
  src/controllers/products/getProductByCategory.ts
  src/controllers/products/index.ts
  src/routers/product.ts
Labels: waiting-review

#94 create order
  src/controllers/orders/createOrder.ts
  src/controllers/orders/index.ts
  src/database/order.ts
  src/routers/index.ts
  src/routers/order.ts
Labels: waiting-review

#96 get all orders adminauth
  src/controllers/orders/getOrders.ts
  src/routers/order.ts
Labels: approved

#98 get user orders
  src/controllers/orders/getUserOrders.ts
  src/routers/order.ts
Labels: waiting-review

#100 delete order
  src/controllers/orders/deleteOrder.ts
  src/routers/index.ts
  src/routers/order.ts
Labels: waiting-review

#101 add query to order router
  src/routers/order.ts
Labels: waiting-review
